/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentaccomodationfinder;
import java.awt.*;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;

/**
 *
 * @author user
 */


public class MainAppWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainAppWindow
     */
private final JTable jTable1;
private final DefaultTableModel tableModel;    
private final JPanel dynamicContentPanel;
private final JLabel messageLabel;

    private static MainAppWindow instance = null;

    public static MainAppWindow getInstance() {
        if (instance == null) {
            instance = new MainAppWindow();
        }
        return instance;
    }


    public MainAppWindow() {
        initComponents();
    search_data.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            search_dataActionPerformed(evt);
        }
    });
    
    messageLabel = new JLabel("", SwingConstants.CENTER);
    tableModel = new DefaultTableModel(new String[]{"House_Id", "Price", "Status", "plotName", "Locality"}, 0);
    jTable1 = new JTable(tableModel);    
    JScrollPane scrollPane = new JScrollPane(jTable1);
    dynamicContentPanel = new JPanel(new BorderLayout());
    dynamicContentPanel.add(scrollPane, BorderLayout.CENTER);
    getContentPane().add(dynamicContentPanel, BorderLayout.CENTER);
    pack();
    setVisible(true);

    // Assuming your search field is named jTextField1
    jTextField1.addFocusListener(new FocusListener() {
    String placeholderText = "Search House by Location, Price or Plotname..";
    @Override
    public void focusGained(FocusEvent e) {
        if (jTextField1.getText().equals(placeholderText)) {
            jTextField1.setText("");
        }
    }
    @Override
    public void focusLost(FocusEvent e) {
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(placeholderText);
        }
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Sign_Out = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search_data = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Plots_In_Nyawita = new javax.swing.JComboBox();
        around_market = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Plots_In_Market = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Plots_In_Vikam = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Plots_In_Mabungo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(0, 0, 255));
        header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 255), new java.awt.Color(153, 153, 255)));
        header.setForeground(new java.awt.Color(0, 0, 255));
        header.setName("Header"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setText("Student Accommodation Finder");

        Sign_Out.setText("Sign_Out");
        Sign_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sign_Out)
                .addGap(6, 6, 6))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Sign_Out)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel2.setText("Famous Locations ...");

        search_data.setText("SEARCH");
        search_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_dataActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Check Reviews About Our App");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(search_data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_data, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        footer.setBackground(new java.awt.Color(0, 0, 255));
        footer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "© 2023 Student Accommodation Finder", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_BOTTOM));
        footer.setForeground(new java.awt.Color(0, 0, 255));
        footer.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("About Us");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Privacy Policy");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Contact Us");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Terms of Service");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel12.setText("Plots Available Around Nyawita.");

        Plots_In_Nyawita.setEditable(true);
        Plots_In_Nyawita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kwa Mama Eugene", "Orange House", "Nyawita Center", "Kwa Mama Ben" }));
        Plots_In_Nyawita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plots_In_NyawitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(Plots_In_Nyawita, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(Plots_In_Nyawita, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel8.setText("Plots Available Around Market.");

        Plots_In_Market.setEditable(true);
        Plots_In_Market.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carolina Herein", "ACK", "The Space", "Food Court" }));
        Plots_In_Market.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plots_In_MarketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout around_marketLayout = new javax.swing.GroupLayout(around_market);
        around_market.setLayout(around_marketLayout);
        around_marketLayout.setHorizontalGroup(
            around_marketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(around_marketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(Plots_In_Market, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        around_marketLayout.setVerticalGroup(
            around_marketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(around_marketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(Plots_In_Market, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel13.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel13.setText("Plots Available Around Vikam.");

        Plots_In_Vikam.setEditable(true);
        Plots_In_Vikam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GV", "Vikam", "Spaace", "Jota" }));
        Plots_In_Vikam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Plots_In_VikamItemStateChanged(evt);
            }
        });
        Plots_In_Vikam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plots_In_VikamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(Plots_In_Vikam, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(Plots_In_Vikam, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jLabel9.setText("Plots Available Around Mabungo.");

        Plots_In_Mabungo.setEditable(true);
        Plots_In_Mabungo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Julias And Dora", "ACK", "Action Center", "Mabungo Center" }));
        Plots_In_Mabungo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plots_In_MabungoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(Plots_In_Mabungo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(Plots_In_Mabungo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(around_market, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(around_market, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sign_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_OutActionPerformed
                 // Instance of Login Window   
        Login_Interface loginWindow = new Login_Interface();
        loginWindow.setVisible(true);
        this.dispose();
                    
    }//GEN-LAST:event_Sign_OutActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Plots_In_NyawitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plots_In_NyawitaActionPerformed
    String selectedItem = (String) Plots_In_Nyawita.getSelectedItem();
    switch (selectedItem) {
        case "Kwa Mama Eugene":
            Kwa_Mama_Eugene detailsFrameKME = new Kwa_Mama_Eugene("Kwa Mama Eugene");
            detailsFrameKME.setVisible(true);
            break;
        case "Orange House":
            Orange_House detailsFrameOH = new Orange_House("Orange House");
            detailsFrameOH.setVisible(true);
            break;
        //case "Jota":
        //    Jota detailsFrameJota = new Jota("Jota");
        //    detailsFrameJota.setVisible(true);
        //    break;
        // Add cases for other plots as needed
    }
    }//GEN-LAST:event_Plots_In_NyawitaActionPerformed

    private void Plots_In_MarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plots_In_MarketActionPerformed
    String selectedItem = (String) Plots_In_Market.getSelectedItem();
    switch (selectedItem) {
        case "The Space":
            The_Space detailsFrameTS = new The_Space("The Space");
            detailsFrameTS.setVisible(true);
            break;
        //case "GV":
        //    GV detailsFrameGV = new GV("GV");
        //    detailsFrameGV.setVisible(true);
        //    break;
        //case "Jota":
        //    Jota detailsFrameJota = new Jota("Jota");
        //    detailsFrameJota.setVisible(true);
        //    break;
        // Add cases for other plots as needed
    }
    }//GEN-LAST:event_Plots_In_MarketActionPerformed

    private void Plots_In_VikamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Plots_In_VikamItemStateChanged
    }//GEN-LAST:event_Plots_In_VikamItemStateChanged

    private void Plots_In_VikamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plots_In_VikamActionPerformed
        String selectedItem = (String) Plots_In_Vikam.getSelectedItem();
    switch (selectedItem) {
        case "Vikam":
            Vikam detailsFrameVK = new Vikam("Vikam");
            detailsFrameVK.setVisible(true);
            break;
        //case "GV":
        //    GV detailsFrameGV = new GV("GV");
        //    detailsFrameGV.setVisible(true);
        //    break;
        //case "Jota":
        //    Jota detailsFrameJota = new Jota("Jota");
        //    detailsFrameJota.setVisible(true);
        //    break;
        // Add cases for other plots as needed
    }
    }//GEN-LAST:event_Plots_In_VikamActionPerformed

    private void Plots_In_MabungoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plots_In_MabungoActionPerformed
    String selectedItem = (String) Plots_In_Mabungo.getSelectedItem();
    switch (selectedItem) {
        case "Action Center":
            Action_Center detailsFrameAC = new Action_Center("Action Center");
            detailsFrameAC.setVisible(true);
            break;
        //case "GV":
        //    GV detailsFrameGV = new GV("GV");
        //    detailsFrameGV.setVisible(true);
        //    break;
        //case "Jota":
        //    Jota detailsFrameJota = new Jota("Jota");
        //    detailsFrameJota.setVisible(true);
        //    break;
        // Add cases for other plots as needed
    }
    }//GEN-LAST:event_Plots_In_MabungoActionPerformed

    private void search_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_dataActionPerformed
System.out.println("search_dataActionPerformed is called");    
        // TODO add your handling code here:
    String searchText = jTextField1.getText().trim();

    if (!searchText.isEmpty()) {
        searchRooms(searchText);
        
        getContentPane().remove(contentPanel);
        JScrollPane scrollPane = new JScrollPane(jTable1);
        getContentPane().add(scrollPane, BorderLayout.CENTER);      
    }  
    }//GEN-LAST:event_search_dataActionPerformed

private void searchRooms(String searchText) {
    tableModel.setRowCount(0);
    String query = "SELECT Room_Id, Price, Status, plotName, Locality FROM room WHERE Locality LIKE ? OR plotName LIKE ? OR Price LIKE ?";

    try (Connection conn = Database.connect();
         PreparedStatement pstmt = conn.prepareStatement(query)) {

        pstmt.setString(1, "%" + searchText + "%");
        pstmt.setString(2, "%" + searchText + "%");
        pstmt.setString(3, "%" + searchText + "%");

        ResultSet rs = pstmt.executeQuery();

        boolean hasData = false;
        while (rs.next()) {
            hasData = true;
            Object[] row = {
                rs.getString("Room_Id"),
                rs.getString("Price"),
                rs.getString("Status"),
                rs.getString("plotName"),
                rs.getString("Locality")
            };
            tableModel.addRow(row);
        }

        if (!hasData) {
            messageLabel.setText("No data found matching your search criteria.");
            updateLayoutForMessage();
        } else {
            updateLayoutForTable();
        }

    } catch (SQLException e) {
        e.printStackTrace(); // Handle exceptions
    }
    System.out.println("Number of rows fetched: " + tableModel.getRowCount());
}

    
    
private void updateLayoutForMessage() {
    System.out.println("Updating layout for message");
    // Remove the table panel and add the message label
    getContentPane().remove(dynamicContentPanel);
    getContentPane().add(messageLabel, BorderLayout.CENTER);
    revalidateAndRepaint();
}

private void updateLayoutForTable() {
    System.out.println("Updating layout for table");
    // Remove the message label and add the table panel
    getContentPane().remove(messageLabel);
    getContentPane().add(dynamicContentPanel, BorderLayout.CENTER);
    revalidateAndRepaint();
}

private void revalidateAndRepaint() {
    // Revalidate and repaint the container to reflect the changes
    getContentPane().revalidate();
    getContentPane().repaint();
    pack();
}





    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    System.out.println("This is main");                
                MainAppWindow.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Plots_In_Mabungo;
    private javax.swing.JComboBox Plots_In_Market;
    private javax.swing.JComboBox Plots_In_Nyawita;
    private javax.swing.JComboBox Plots_In_Vikam;
    private javax.swing.JButton Sign_Out;
    private javax.swing.JPanel around_market;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton search_data;
    // End of variables declaration//GEN-END:variables
}
